Portfolio desktop version
akbarsazish/portfolio pull request #5
Opened 2023-05-11 21:45 UTC by akbarsazish

I have submitted a project, that uses a pull request that has already been approved, therefore I created new branch and pushed all desktop version code at once.

2023-05-11 22:56 UTC, Strangeal requested changes
Hi @akbarsazish, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅
Descriptive PR title with a great summary ✅

## Required Changes ♻️
- [ ] Impressive 👏 work so far on implementing most of the project requirements. I've made some comments below which will guide you to improve 🚀 your design so please take your time and go through them and if you don't understand anything please don't hesitate to ask. Best of luck 🍀🤞
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 22:56 UTC, Strangeal commented on assets/style.css
>    color: #6070ff;
- [ ] Kindly consider reducing the `border-radius` as it doesn't match with the `Figma` design. Your design needs to look like that of the `Figma` template you have chosen as much as possible. This will help you to pay more attention to the details of designs when given to you. Attention to detail is an important skill we need to develop as developers. See below for more details: 
<table>
<tr>
<th align="middle">Figma design</th>
<th align="middle">Your design</th>
</tr>
<tr>
<td>
<img width="375" alt="Screenshot 2023-05-11 at 22 06 08" src="https://github.com/akbarsazish/portfolio/assets/107192076/3fa70457-3138-4867-b319-ea4f1653c08e">
</td>
<td>
<img width="542" alt="Screenshot 2023-05-11 at 21 56 38" src="https://github.com/akbarsazish/portfolio/assets/107192076/806a6cff-ef08-433c-9c44-cef6c89fea59">
</td>
</tr>
</table>

2023-05-11 22:56 UTC, Strangeal commented on assets/style.css
>  .see-project {
- [ ] Kindly consider giving your `button` a `background: transparent;` so it looks like that of the `Figma` design given. Your design needs to look like that of the `Figma` template you have chosen as much as possible. This will help you to pay more attention to the details of designs when given to you. Attention to detail is an important skill we need to develop as developers. See below for more details: 
<table>
<tr>
<th align="middle">Figma design</th>
<th align="middle">Your design</th>
</tr>
<tr>
<td>
<img width="148" alt="Screenshot 2023-05-11 at 22 11 51" src="https://github.com/akbarsazish/portfolio/assets/107192076/32b70fe0-b818-46e6-9518-45f8dd3d207d">
</td>
<td>
<img width="164" alt="Screenshot 2023-05-11 at 21 57 04" src="https://github.com/akbarsazish/portfolio/assets/107192076/239d99f9-df4e-4a75-99b5-2918f8a55530">
</td>
</tr>
</table>

2023-05-11 22:56 UTC, Strangeal commented on assets/style.css
>  }
- [ ] Kindly consider styling the `accordion` section to match that of the `Figma` design template as it currently doesn't match with it. Your design needs to look like that of the `Figma` design template you have chosen as much as possible. This will help make your design look more attractive and create a good user experience. See below for more details: 
<table>
<tr>
<th align="middle">Figma design</th>
<th align="middle">Your design</th>
</tr>
<tr>
<td>
<img width="724" alt="Screenshot 2023-05-11 at 22 15 29" src="https://github.com/akbarsazish/portfolio/assets/107192076/35b58b7c-28a0-4783-a06c-c3daaf03fc46">
</td>
<td>
<img width="665" alt="Screenshot 2023-05-11 at 22 15 56" src="https://github.com/akbarsazish/portfolio/assets/107192076/a985ce3c-1f26-486e-b1bf-9e212583acc3">
</td>
</tr>
</table>

- [ ] Also adjust the `padding` around the `About` section to match that of the `Figma` design. This will help make you design look beautiful 😍 🤩  and create a good user experience. Again please make sure to pay attention to the details of the design as much as possible because this is an important skill to have as a developer. See below for more details:
<table>
<tr>
<th align="middle">Figma design</th>
<th align="middle">Your design</th>
</tr>
<tr>
<td>
<img width="1437" alt="Screenshot 2023-05-11 at 22 25 40" src="https://github.com/akbarsazish/portfolio/assets/107192076/1e6b8647-a39b-46b9-8465-4e420ad88b7f">
</td>
<td>
<img width="1430" alt="Screenshot 2023-05-11 at 22 23 31" src="https://github.com/akbarsazish/portfolio/assets/107192076/778eeeef-a308-47f3-af92-8f5e98bab5f7">
</td>
</tr>
</table>

2023-05-11 22:56 UTC, Strangeal commented on assets/mediaquery.css
> +  }
- [ ] Kindly consider the below suggestions which will guide you to improve your design. Your design looks great on `desktop` view but when tested on `mobile` and `tablet` screens it doesn't look as good as expected which doesn’t create a good user experience because some of your users will be accessing your portfolio through some of this devices and it would be bad for them to see your portfolio in that shape.
    - [ ] Your styles on `mobile` should not be affected by the styles you implement on `desktop`.  This can be done by using `media queries` as you have done but please take your time and add and remove some styles to make the consistent on of screen sizes (mobile, tablet, and desktop)`.  See below for more details on some issues with your design:
 <table>
<tr>
<th align="middle">Work section</th>
<th align="middle">About section</th>
</tr>
<tr>
<td>
<img width="404" alt="Screenshot 2023-05-11 at 22 33 43" src="https://github.com/akbarsazish/portfolio/assets/107192076/193cfaeb-ce62-4989-a9b9-548e2c81d59b">
<img width="776" alt="Screenshot 2023-05-11 at 22 32 35" src="https://github.com/akbarsazish/portfolio/assets/107192076/39d0106b-225a-4f0f-b9a2-6ba41f8d2cdf">

</td>
<td>
<img width="404" alt="Screenshot 2023-05-11 at 22 34 49" src="https://github.com/akbarsazish/portfolio/assets/107192076/aad87f7f-1d31-4586-b921-d1d513570e9c">

</td>
</tr>
</table>

2023-05-11 23:31 UTC, akbarsazish commented
Hi @Strangeal, Your recommendation has made a huge difference in my project and I'm so thankful for your advise and feedback.

2023-05-12 06:37 UTC, akbarsazish commented on assets/mediaquery.css
> +  }
> 
Hi @Strangeal, I hope this message finds you well. I was wondering if you could lend me a hand with something. I'm struggling with mobile-first design and was hoping you could explain it to me or give me some tips on how to approach it. I appreciate any help you can offer.

Thank you so much in advance!

2023-05-12 10:59 UTC, Strangeal commented on assets/mediaquery.css
> +  }
@akbarsazish, sorry for the late reply, Yes. I can help you with that anytime you're ready. Just let me know the time and I will be there to help.

2023-05-12 17:39 UTC, AdnanOlarmmi requested changes
Hi @akbarsazish, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Fixed some of reviewer's changes.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 17:39 UTC, AdnanOlarmmi commented on assets/mediaquery.css
> +  }
> * [ ]  Kindly consider the below suggestions which will guide you to improve your design. Your design looks great on `desktop` view but when tested on `mobile` and `tablet` screens it doesn't look as good as expected which doesn’t create a good user experience because some of your users will be accessing your portfolio through some of this devices and it would be bad for them to see your portfolio in that shape.
>   
>   * [ ]  Your styles on `mobile` should not be affected by the styles you implement on `desktop`.  This can be done by using `media queries` as you have done but please take your time and add and remove some styles to make the consistent on of screen sizes (mobile, tablet, and desktop)`.  See below for more details on some issues with your design:
> 
> Work section	About section
> <img alt="Screenshot 2023-05-11 at 22 33 43" width="404" src="https://user-images.githubusercontent.com/107192076/237828687-193cfaeb-ce62-4989-a9b9-548e2c81d59b.png"> <img alt="Screenshot 2023-05-11 at 22 32 35" width="776" src="https://user-images.githubusercontent.com/107192076/237828852-39d0106b-225a-4f0f-b9a2-6ba41f8d2cdf.png">	<img alt="Screenshot 2023-05-11 at 22 34 49" width="404" src="https://user-images.githubusercontent.com/107192076/237829013-aad87f7f-1d31-4586-b921-d1d513570e9c.png">

- [ ] Just like the previous reviewer said, your card tiles are meant to alternate, not on the same row. And all these fixes are yet to work
![mobile](https://github.com/akbarsazish/portfolio/assets/41163571/2e38989f-fd83-45d2-bbe4-3b548a842e43)

2023-05-12 17:39 UTC, AdnanOlarmmi commented on assets/style.css
>  }
> * [ ]  Kindly consider styling the `accordion` section to match that of the `Figma` design template as it currently doesn't match with it. Your design needs to look like that of the `Figma` design template you have chosen as much as possible. This will help make your design look more attractive and create a good user experience. See below for more details:
> 
> Figma design	Your design
> <img alt="Screenshot 2023-05-11 at 22 25 40" width="1437" src="https://user-images.githubusercontent.com/107192076/237826380-1e6b8647-a39b-46b9-8465-4e420ad88b7f.png">	<img alt="Screenshot 2023-05-11 at 22 23 31" width="1430" src="https://user-images.githubusercontent.com/107192076/237826356-778eeeef-a308-47f3-af92-8f5e98bab5f7.png">

- [ ] Like the previous reviewer mentioned, also the accordion section is meant to stretch more than the length of the About Myself section.

2023-05-12 17:39 UTC, AdnanOlarmmi commented on assets/style.css
>  .see-project {
> * [ ]  Kindly consider giving your `button` a `background: transparent;` so it looks like that of the `Figma` design given. Your design needs to look like that of the `Figma` template you have chosen as much as possible. This will help you to pay more attention to the details of designs when given to you. Attention to detail is an important skill we need to develop as developers. See below for more details:
> 
> Figma design	Your design
> <img alt="Screenshot 2023-05-11 at 22 11 51" width="148" src="https://user-images.githubusercontent.com/107192076/237824145-32b70fe0-b818-46e6-9518-45f8dd3d207d.png">	<img alt="Screenshot 2023-05-11 at 21 57 04" width="164" src="https://user-images.githubusercontent.com/107192076/237824197-239d99f9-df4e-4a75-99b5-2918f8a55530.png">

- [ ] [OPTIONAL] This is also applicable to the Get my resume button below.
<img width="105" alt="image" src="https://github.com/akbarsazish/portfolio/assets/41163571/245c4f37-060d-4814-8b79-28ba20429a89">

2023-05-13 15:02 UTC, akbarsazish commented
Hello, I hope this message finds you will, this is my last pull request and I would like to request if this pull request needs any changes please message me to bring the required change.
My email:  sazishaliakbar@gmail.com
My WhatsApp: +989100473242

2023-05-13 15:26 UTC, Zuhaib042 approved these changes
Hi @akbarsazish 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/n58MqIchLqAalRQAQB/giphy.gif)
## Highlights
✅ Implemented suggested changes
✅ Linters passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 15:26 UTC, Zuhaib042 commented on assets/style.css
>    background-color: #e5e5e5;
- [OPTIONAL] This bug was missed by the previous reviewer, and I highly recommend you to fix this. The background color of the entire body is `#f4f5f7`. so kindly replace this `e5e5e5` color with the one I mentioned.
Then you would need to give your hero section `#fff` background color to make your styling identicalto the figma design.
kindly look at your design, and see the difference
your design
![qw](https://github.com/akbarsazish/portfolio/assets/96683843/0929e19b-295f-4ea7-b67e-e15bad868d23)

figma design

 
![r](https://github.com/akbarsazish/portfolio/assets/96683843/92ac75a5-06f5-4b05-a9ac-ca1eb836500d)

2023-05-13 15:55 UTC, merged